# Generated by Django 3.2.12 on 2022-04-30 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AccountApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='uyelik',
            table='Uyelikler',
        ),
    ]
