# Generated by Django 3.2.12 on 2022-04-30 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AccountApp', '0002_alter_uyelik_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uyelik',
            options={'verbose_name': 'Üye', 'verbose_name_plural': 'Üyelikler'},
        ),
        migrations.AlterModelTable(
            name='uyelik',
            table=None,
        ),
    ]
