# Generated by Django 3.2.12 on 2022-04-30 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AccountApp', '0003_auto_20220430_2000'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uyelik',
            options={'verbose_name': 'Üyelik Tipi', 'verbose_name_plural': 'Üyelik Tipleri'},
        ),
    ]
