# Generated by Django 3.2.12 on 2022-04-21 17:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='diller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dil', models.CharField(max_length=15, unique=True, verbose_name="Dil'i Girin :")),
            ],
        ),
        migrations.CreateModel(
            name='filmler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filmAdi', models.CharField(max_length=50, verbose_name='Film Adı :')),
                ('filmKonusu', models.TextField(blank=True, max_length=500, null=True, verbose_name='Konu :')),
                ('film', models.FileField(upload_to='movies/', verbose_name='Filmi yükle :')),
                ('filmPoster', models.FileField(blank=True, null=True, upload_to='posters/', verbose_name='Film Posteri :')),
                ('filmSlug', models.SlugField(unique=True)),
                ('ulke', models.CharField(max_length=85, verbose_name='Ülke Adını Girin :')),
                ('yapimYili', models.DateField(null=True)),
                ('kalite', models.CharField(choices=[('144px', '144px'), ('240px', '240px'), ('360px', '360px'), ('480px', '480px'), ('720px', '720px'), ('1280px', '1280px')], max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='kategoriler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategori', models.CharField(max_length=30, unique=True, verbose_name='Kategoriyi Girin :')),
            ],
        ),
        migrations.CreateModel(
            name='yorumlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yorum', models.TextField(max_length=500)),
                ('kullanici_adi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
