# Generated by Django 3.2.12 on 2022-04-21 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieApp', '0002_filmler_kategoriler'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmler',
            name='diller',
            field=models.ManyToManyField(to='MovieApp.diller'),
        ),
    ]
