# Generated by Django 3.2.12 on 2022-04-22 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MovieApp', '0005_remove_filmler_film_yorumlar'),
    ]

    operations = [
        migrations.AddField(
            model_name='yorumlar',
            name='film',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MovieApp.filmler'),
        ),
    ]
