# Generated by Django 3.2.12 on 2022-04-30 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MovieApp', '0006_yorumlar_film'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filmler',
            options={'verbose_name': 'Film', 'verbose_name_plural': 'Filmler'},
        ),
        migrations.AlterModelOptions(
            name='kategoriler',
            options={'verbose_name': 'Kategori', 'verbose_name_plural': 'Kategoriler'},
        ),
        migrations.AlterModelOptions(
            name='yorumlar',
            options={'verbose_name': 'Yorum', 'verbose_name_plural': 'Yorumlar'},
        ),
    ]
