# Generated by Django 3.2.12 on 2022-04-30 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MovieApp', '0007_auto_20220430_2008'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diller',
            options={'verbose_name': 'Dil', 'verbose_name_plural': 'Diller'},
        ),
    ]
