# Generated by Django 3.2.12 on 2022-05-05 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MovieApp', '0008_alter_diller_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='yorumlar',
            old_name='kullanici_adi',
            new_name='kullanici',
        ),
    ]
